spring:
  application:
    name: myapp
  profiles:
    active: dev # default profile
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect